apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-limit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request-limit
  template:
    metadata:
      labels:
        app: request-limit
    spec:
      containers:
        - name: request-limit
          image: gcr.io/kubernetes-e2e-test-images/resource-consumer:1.4
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "500m"
          command:
            - "/consumer"
            - -port
            - "8080"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-request-limit
spec:
  selector:
    app: request-limit
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer